import type { Metadata } from "next";
import { AuthProvider } from "../context/auth/AuthContext";
import { DashboardProvider } from "../context/dashboard/DashboardContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Workhub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <DashboardProvider>{children}</DashboardProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
